name: mhciipresentation
channels:
  - defaults
  - fastai
  - pytorch
  - bioconda
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - biopython>=1.79
  - debugpy>=1.4.1
  - ipykernel>=6.4.1
  - jax>=0.2.21
  - jedi>=0.18.0
  - jupyterlab>=3.1.13
  - matplotlib>=3.4.2
  - mkdocs=1.2.2
  - mkdocs-autorefs>=0.2.1
  - mkdocs-material-extensions>=1.0.1
  - mkdocstrings>=0.16.1
  - mypy>=0.910
  - mypy_extensions>=0.4.3
  - networkx>=2.6.3
  - notebook>=6.4.3
  - numpy>=1.19.5
  - openpyxl>=3.0.9
  - packaging>=21.0
  - pandocfilters>=1.4.3
  - pickleshare>=0.7.5
  - pip>=21.2.4
  - pymdown-extensions>=8.2
  - python>=3.9.7
  - pytorch>=1.9.1
  - scikit-learn>=0.24.2
  - setuptools>=58.0.4
  - statsmodels>=0.12.2
  - virtualenv>=20.4.7
  - xgboost
  - isort>=5.9.3
  - mypy>=0.910
  - pytest>=6.2.4
  - black
  - decorator>=5.0.9
  - h5py>=3.1.0
  - pandas>=1.2.4
  - pre-commit>=2.13.0
  - tqdm>=4.61.1
  - scipy>=1.6.1
  - seaborn>=0.11.1
  - tabulate>=0.8.9
  - typing-extensions>=3.7.4.3
  - graphviz
  - mypy
  - pip:
      - streamlit>=1.1.0
