
defaults:
  - _self_
  - compute: compute_cluster
  - model: aegis_model
  - training: training
  - seed: seed
  - debug: debug
  - dataset: dataset
  - paths: paths
    
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}