epochs: 50
min_steps: 10
batch_size: 64
learning_rate:
  start_learning_rate: 0.001
  peak_learning_rate: 0.001
  warmup_steps: 10
  reduction_factor: 2
  patience: 1
optimizer:
  weight_decay: 1.0e-3
check_val_every_n_epoch: 1
early_stopping:
  min_delta: 0.00
  patience: 1
  monitor: "val_loss/dataloader_idx_0"
  mode: "min"
